### PR TITLE
Add: wit.ai in libraries section

### PR DESCRIPTION
**Pull request by vs1682**
wit-ai is a part of facebook.
It has libraries for 
  - Pyhton
  - Ruby
  - Nodejs

### CODE REVIEW

**Comment by keonkim** [comment]
@vs1682 I guess wit.ai is a web API or service than a library.
Maybe we should make another section for services(API).

**Comment by vs1682** [comment]
Yes. It's an API.
I'll update the PR with a new section as APIs.

**Comment by vs1682** [comment]
And where should I create the section as creating it below credits won't look good.
Why don't you add a contribution file.

**Comment by keonkim** [comment]
@vs1682 sorry for the late response.
Adding a `services` or `API` section below `Libraries` seems to be reasonable.
Contribution file seems to be a good idea, I will put that on my list :).

**Comment by vs1682** [comment]
@keonkim I have added services or API section and moved wit-ai to it.

**Comment by keonkim** [comment]
@vs1682 thanks!

**Pull request merged**
